coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true

ignore:
  - "drizzle/migrations"
  - "scripts"
  - "**/*.config.ts"
