coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 0.5%
    patch:
      default:
        target: 70%

comment:
  layout: "condensed_header, condensed_files, condensed_footer"
  require_changes: true

ignore:
  - "**/*.config.ts"
  - "components/ui/**"
  - "drizzle/migrations"
  - "e2e"
  - "scripts"
  - "server/emails/**"
