/**
 * Shared schema mock for Stripe service tests.
 *
 * Bun's mock.module is global per test run, so every test file that mocks
 * @/server/db/schema must export ALL named exports the real schema provides.
 * Otherwise, a test file that only exports `payments` will break another
 * file that needs `clients`.
 */
export const schemaMock = {
  clients: {
    id: 'clients.id',
    stripeCustomerId: 'clients.stripe_customer_id',
    stripeCardPaymentMethodId: 'clients.stripe_card_payment_method_id',
    stripeAchPaymentMethodId: 'clients.stripe_ach_payment_method_id',
  },
  clinics: { id: 'clinics.id' },
  plans: { id: 'plans.id', status: 'plans.status', remainingCents: 'plans.remaining_cents' },
  payments: { id: 'payments.id', stripePaymentIntentId: 'payments.stripe_payment_intent_id' },
  payouts: { id: 'payouts.id' },
  auditLog: {
    id: 'auditLog.id',
    entityType: 'auditLog.entity_type',
    entityId: 'auditLog.entity_id',
    createdAt: 'auditLog.created_at',
  },
  riskPool: {
    id: 'riskPool.id',
    type: 'riskPool.type',
    contributionCents: 'riskPool.contribution_cents',
  },
  pets: {
    id: 'pets.id',
    clientId: 'pets.client_id',
    name: 'pets.name',
    species: 'pets.species',
    breed: 'pets.breed',
    age: 'pets.age',
    createdAt: 'pets.created_at',
    updatedAt: 'pets.updated_at',
  },
  softCollections: {
    id: 'soft_collections.id',
    planId: 'soft_collections.plan_id',
    stage: 'soft_collections.stage',
    startedAt: 'soft_collections.started_at',
    lastEscalatedAt: 'soft_collections.last_escalated_at',
    nextEscalationAt: 'soft_collections.next_escalation_at',
    notes: 'soft_collections.notes',
    createdAt: 'soft_collections.created_at',
    updatedAt: 'soft_collections.updated_at',
  },
  clinicStatusEnum: {},
  paymentMethodEnum: {},
  planStatusEnum: {},
  paymentTypeEnum: {},
  paymentStatusEnum: {},
  payoutStatusEnum: {},
  riskPoolTypeEnum: {},
  actorTypeEnum: {},
  softCollectionStageEnum: {},
  apiKeys: {
    id: 'api_keys.id',
    clinicId: 'api_keys.clinic_id',
    name: 'api_keys.name',
    keyHash: 'api_keys.key_hash',
    keyPrefix: 'api_keys.key_prefix',
    permissions: 'api_keys.permissions',
    lastUsedAt: 'api_keys.last_used_at',
    expiresAt: 'api_keys.expires_at',
    allowedIps: 'api_keys.allowed_ips',
    createdAt: 'api_keys.created_at',
    revokedAt: 'api_keys.revoked_at',
  },
  paymentMethods: {
    id: 'payment_methods.id',
    clientId: 'payment_methods.client_id',
  },
  idempotencyKeys: {
    id: 'idempotency_keys.id',
    clinicId: 'idempotency_keys.clinic_id',
    idempotencyKey: 'idempotency_keys.idempotency_key',
    httpMethod: 'idempotency_keys.http_method',
    httpPath: 'idempotency_keys.http_path',
    responseStatus: 'idempotency_keys.response_status',
    responseBody: 'idempotency_keys.response_body',
    createdAt: 'idempotency_keys.created_at',
    expiresAt: 'idempotency_keys.expires_at',
  },
  webhookEndpoints: {
    id: 'webhook_endpoints.id',
    clinicId: 'webhook_endpoints.clinic_id',
    url: 'webhook_endpoints.url',
    secret: 'webhook_endpoints.secret',
    events: 'webhook_endpoints.events',
    enabled: 'webhook_endpoints.enabled',
    description: 'webhook_endpoints.description',
    createdAt: 'webhook_endpoints.created_at',
    updatedAt: 'webhook_endpoints.updated_at',
  },
  webhookDeliveries: {
    id: 'webhook_deliveries.id',
    endpointId: 'webhook_deliveries.endpoint_id',
    eventType: 'webhook_deliveries.event_type',
    payload: 'webhook_deliveries.payload',
    status: 'webhook_deliveries.status',
    httpStatus: 'webhook_deliveries.http_status',
    responseBody: 'webhook_deliveries.response_body',
    attempts: 'webhook_deliveries.attempts',
    nextRetryAt: 'webhook_deliveries.next_retry_at',
    createdAt: 'webhook_deliveries.created_at',
    completedAt: 'webhook_deliveries.completed_at',
  },
  webhookDeliveryStatusEnum: {},
  referralStatusEnum: {},
  clinicRequests: {
    id: 'clinic_requests.id',
    clientEmail: 'clinic_requests.client_email',
    clinicName: 'clinic_requests.clinic_name',
  },
  clinicReferrals: {
    id: 'clinic_referrals.id',
    referrerClinicId: 'clinic_referrals.referrer_clinic_id',
    referralCode: 'clinic_referrals.referral_code',
    status: 'clinic_referrals.status',
  },
  clientReferrals: {
    id: 'client_referrals.id',
    referrerClientId: 'client_referrals.referrer_client_id',
    referralCode: 'client_referrals.referral_code',
    status: 'client_referrals.status',
    creditApplied: 'client_referrals.credit_applied',
  },
  paymentMethodsRelations: {},
  clinicsRelations: {},
  clientsRelations: {},
  petsRelations: {},
  plansRelations: {},
  paymentsRelations: {},
  payoutsRelations: {},
  riskPoolRelations: {},
  softCollectionsRelations: {},
  apiKeysRelations: {},
  webhookEndpointsRelations: {},
  webhookDeliveriesRelations: {},
  clinicReferralsRelations: {},
  clientReferralsRelations: {},
  knowledgeChunks: {
    id: 'knowledge_chunks.id',
    source: 'knowledge_chunks.source',
    title: 'knowledge_chunks.title',
    content: 'knowledge_chunks.content',
    embedding: 'knowledge_chunks.embedding',
    metadata: 'knowledge_chunks.metadata',
    createdAt: 'knowledge_chunks.created_at',
    updatedAt: 'knowledge_chunks.updated_at',
  },
  chatSessions: {
    id: 'chat_sessions.id',
    userId: 'chat_sessions.user_id',
    userRole: 'chat_sessions.user_role',
    messages: 'chat_sessions.messages',
    helpful: 'chat_sessions.helpful',
    createdAt: 'chat_sessions.created_at',
    updatedAt: 'chat_sessions.updated_at',
  },
};
